#!/bin/bash
# scripts/deploy.sh
# 
# Description: Automates the installation of a DolphinDB Single Node.
# Usage: ./deploy.sh [VERSION] [PORT] [INSTALL_DIR]
# Example: ./deploy.sh 3.00.4.0 8848 /data/dolphindb/node1

set -e

# --- Configuration ---
VERSION=${1:-"3.00.4.0"}
PORT=${2:-8848}
INSTALL_DIR=${3:-"$HOME/dolphindb_single"}

# URL construction logic
DDB_URL="https://www.dolphindb.cn/downloads/DolphinDB_Linux64_V${VERSION}.zip"

# Paths
SERVER_ROOT="$INSTALL_DIR/server"
SERVER_BIN="$SERVER_ROOT/server"
CFG_FILE="$SERVER_BIN/dolphindb.cfg"
LOG_FILE="$SERVER_BIN/dolphindb.log"

echo "=== DolphinDB Deployment Agent ==="
echo "Target Version : $VERSION"
echo "Target Port    : $PORT"
echo "Install Path   : $INSTALL_DIR"
echo "=================================="

# 1. Check for Existing Installation / Cleanup
if [ -d "$INSTALL_DIR" ]; then
    echo "[Info] Target directory exists."
    # Check if we should backup or just use it
    if [ -f "$INSTALL_DIR/dolphindb.zip" ]; then
        echo "[Info] Found dolphindb.zip, skipping backup to reuse it."
    else
        echo "[Warn] Backing up existing directory..."
        TIMESTAMP=$(date +%Y%m%d%H%M%S)
        mv "$INSTALL_DIR" "${INSTALL_DIR}_bak_${TIMESTAMP}"
        mkdir -p "$INSTALL_DIR"
    fi
else
    mkdir -p "$INSTALL_DIR"
fi

cd "$INSTALL_DIR"

# 2. Download (Smart Skip)
if [ -f "dolphindb.zip" ]; then
    echo "[Skip] 'dolphindb.zip' already exists in $INSTALL_DIR. Using local copy."
else
    echo "[Action] Downloading DolphinDB package..."
    if ! wget -q "$DDB_URL" -O dolphindb.zip; then
        echo "[Error] Failed to download from $DDB_URL. Check version number or network."
        exit 1
    fi
fi

# 3. Extract (Always refresh binaries)
echo "[Action] Extracting package..."
# -u: update files, -o: overwrite existing
unzip -q -o dolphindb.zip -d server

# 4. Configuration (The Critical Part)
echo "[Action] Configuring dolphindb.cfg..."
if [ ! -f "$CFG_FILE" ]; then
    echo "[Error] dolphindb.cfg not found at $CFG_FILE"
    exit 1
fi

# Detect Local IP (First non-loopback)
# This command gets the first IP address that is not 127.0.0.1
# If hostname -I fails, try ip addr
LOCAL_IP=$(hostname -I | awk '{print $1}')
if [ -z "$LOCAL_IP" ]; then 
    LOCAL_IP="0.0.0.0" 
    echo "[Warn] Could not detect IP, binding to 0.0.0.0"
fi

echo "         > Binding to IP: $LOCAL_IP"
echo "         > Binding to Port: $PORT"

# Clean Config: Create a fresh config tailored for Single Node
# We backup the default one first
cp "$CFG_FILE" "${CFG_FILE}.default"

# Write new config
cat <<EOF > "$CFG_FILE"
# Generated by Deployment Script
mode=single
localSite=$LOCAL_IP:$PORT:local$PORT
maxMemSize=4
maxConnections=512
workerNum=4
# Log to file, not stdout/stderr
console=0
EOF

# 5. Script Generation
echo "[Action] Generating management scripts..."
cd "$SERVER_BIN"
chmod +x dolphindb

# Create start.sh
# NOTE: We do NOT pass -localSite here to avoid conflict with dolphindb.cfg
cat <<EOF > start.sh
#!/bin/bash
APP_NAME="dolphindb-port-$PORT"
# Start using config file only
nohup ./dolphindb -logFile dolphindb.log > single.nohup 2>&1 &
PID=\$!
echo "Started DolphinDB (PID: \$PID)"
echo "Logs: $SERVER_BIN/dolphindb.log"
sleep 1
EOF
chmod +x start.sh

# Create stop.sh
cat <<EOF > stop.sh
#!/bin/bash
# SAFE STOP: Only kill the process listening on our specific port
PID=\$(lsof -t -i:$PORT -sTCP:LISTEN)
if [ -n "\$PID" ]; then
    kill \$PID
    echo "Stopped DolphinDB (PID: \$PID) on port $PORT"
else
    echo "No process found listening on port $PORT."
fi
EOF
chmod +x stop.sh

# 6. Start Service
echo "[Action] Starting Service..."
# Kill any existing process on this port first
./stop.sh
sleep 2
./start.sh

# 7. Verification
echo "[Action] Verifying startup..."
sleep 5 # Wait for initialization

# Check if process is alive
if ps aux | grep -v grep | grep "dolphindb" > /dev/null; then
    echo "✅ Process is running."
else
    echo "❌ Process died immediately. Last logs:"
    tail -n 10 dolphindb.log
    exit 1
fi

# Check if port is listening (Try multiple methods)
echo "         > Checking Port $PORT..."
if netstat -tulnp 2>/dev/null | grep ":$PORT " > /dev/null; then
    echo "✅ SUCCESS: Port $PORT is listening."
    echo "   - Web URL: http://$LOCAL_IP:$PORT"
elif ss -tulnp 2>/dev/null | grep ":$PORT " > /dev/null; then
    echo "✅ SUCCESS: Port $PORT is listening (verified via ss)."
    echo "   - Web URL: http://$LOCAL_IP:$PORT"
else
    echo "⚠️  WARNING: Process is up but Port $PORT not detected by netstat/ss."
    echo "   This might be a permission issue or the server is binding to IPv6/different interface."
    echo "   Please check logs manually: $SERVER_BIN/dolphindb.log"
    # Don't exit 1 here, as it might just be a detection issue in some environments
fi
